# Generated by Django 3.2.16 on 2023-03-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
