# Generated by Django 3.2.16 on 2023-04-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20230402_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_eur',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_usd',
            field=models.IntegerField(default=0),
        ),
    ]
